#!/usr/bin/env bash

set -euo pipefail

banner=$(cat << END
 **********************************************************                                                            
           mm                                               
           ##                                               
 mm#####m  ##m####m   m####m    ##m####   ##m####  "##  ### 
 ##mmmm "  ##"   ##  ##mmmm##   ##"       ##"       ##m ##  
  """"##m  ##    ##  ##""""""   ##        ##         ####"  
 #mmmmm##  ##    ##  "##mmmm#   ##        ##          ###   
  """"""   ""    ""    """""    ""        ""          ##    
                                                    ###     
 ******* Automatic Shell Environment Setup Tool *********** 

END
)

echo "$banner"
echo

if (( EUID == 0 )); then
    echo 'This installer must not be run as root.' >&2
    exit 1
fi

if [[ ! -r /etc/os-release ]]; then
    echo 'Unable to determine the Linux distribution: /etc/os-release is unavailable.' >&2
    exit 1
fi

# /etc/os-release is a system-provided file containing shell-compatible variables.
# shellcheck disable=SC1091
source /etc/os-release
if [[ ${ID:-} != opensuse* && ${ID_LIKE:-} != *opensuse* && ${ID_LIKE:-} != *suse* ]]; then
    echo "Unsupported distribution: ${PRETTY_NAME:-unknown}. This installer requires openSUSE." >&2
    exit 1
fi

for command in zypper sudo git id getent; do
    if ! command -v "$command" > /dev/null 2>&1; then
        echo "Required command not found: $command" >&2
        exit 1
    fi
done

echo " * Finding the location of the script..."

# shellcheck disable=SC2128
if [[ $BASH_SOURCE = */* ]]; then
    datadir="${BASH_SOURCE%/*}/"
else
    datadir="./"
fi

echo -n ' * Detecting your shell... '

current_user=$(id -un)
if ! passwd_entry=$(getent passwd "$current_user"); then
    echo "Unable to find the account entry for $current_user." >&2
    exit 1
fi
getshell=${passwd_entry##*:}

if [[ ${getshell##*/} == bash ]]; then
    echo "bash."
    shrc="$HOME/.bashrc"
else
    echo 'Unsupported shell, aborting.'
    exit 1
fi

if [[ -L "$shrc" ]]; then
    if [[ ! -e "$shrc" ]]; then
        echo "Cannot update $shrc: it is a broken symbolic link." >&2
        exit 1
    fi
    shrc_target=$(realpath "$shrc")
else
    shrc_target="$shrc"
fi

shrc_tmp=$(mktemp "${shrc_target}.sherry.XXXXXX")
cleanup() {
    if [[ -n ${shrc_tmp:-} ]]; then
        rm -f -- "$shrc_tmp"
    fi
}
trap cleanup EXIT

if [[ -e "$shrc" ]]; then
    cp --preserve=mode -- "$shrc" "$shrc_tmp"
fi

if grep -Eq '^# (begin sherry([[:space:]]|$)|end sherry$)' "$shrc_tmp"; then
    echo "Sherry configuration already exists in $shrc; no changes were made." >&2
    exit 1
fi

# install necessary packages
echo -n
echo -n "Please enter your password to install packages via zypper: "
read -rs passwd
printf '\n * Installing developer tools...\n'
echo "$passwd" | sudo -S zypper --non-interactive install -t pattern devel_basis
echo "$passwd" | sudo -S zypper --non-interactive install clang clang-devel clang-tools
echo "$passwd" | sudo -S zypper --non-interactive install glibc-devel-static scdoc
printf '\n * Installing useful command line utilities...\n'
echo "$passwd" | sudo -S zypper --non-interactive install starship zoxide ripgrep findutils gnu_parallel neovim autoconf \
    mc jq btop gdu tmux bc curl wget lazygit

echo -n
echo -n "Installing Bitwarden dependencies..."
echo "$passwd" | sudo -S zypper --non-interactive install libnotify-tools

# BWURL=$(curl -fsSL https://api.github.com/repos/bitwarden/clients/releases | jq -r 'first(.[] | .assets[]? | select(.browser_download_url | endswith(".rpm")) | .browser_download_url)')
# 
# if [ -n "$BWURL" ]; then
#     echo "Downloading Bitwarden from $BWURL"
#     curl -L -o "${datadir}bitwarden-latest.rpm" "$BWURL" 
# else
#     echo "--- Could not find Bitwarden RPM URL"
#     exit 1
# fi
# 
# if test -f "${datadir}bitwarden-latest.rpm"; then
#     echo "$passwd" | sudo -S rpm -i ${datadir}bitwarden-latest.rpm
# fi
# 
# rm "${datadir}bitwarden-latest.rpm"

# shellcheck disable=SC2129
echo >> "$shrc_tmp"
echo "# begin sherry (the following lines have been automatically added by sherry)" >> "$shrc_tmp"
echo >> "$shrc_tmp"

# fzf
if [ ! -d "$HOME/.fzf" ]; then
    echo ' * Installing FZF...'
    echo
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --key-bindings --completion --no-update-rc
else 
    echo ' * FZF already installed.'
fi
echo '[ -f ~/.fzf.bash ] && source ~/.fzf.bash' >> "$shrc_tmp"

# configure case-insensitive autocompletion
if [ ! -f "$HOME/.inputrc" ]; then
    echo 'Configuring case-insensitive autocompletion...'
    echo
    # shellcheck disable=SC2016
    echo '$include /etc/inputrc' > ~/.inputrc
    echo 'set completion-ignore-case On' >> ~/.inputrc
else 
    echo ' * .inputrc already present.'
fi

echo ' * Adding shell files to .bashrc...'
for file in "$datadir"shell/*.sh; do
    echo "   * Sourcing $file"
    printf 'source %q\n' "$(realpath "$file")" >> "$shrc_tmp"
done
echo

echo " * Linking other configuration files into $HOME..."

shopt -s dotglob
for file in "$datadir"*; do
    basefilename=$( basename "$file" )
    realfilepath=$( realpath "$file" )
    homelinkpath="$HOME/$basefilename"
    if [ -f "$file" ] && [[ "$basefilename" = .* ]] && ! [[ "$basefilename" = ".gitmodules" ]]; then
        # this together with the -f option for ln takes care of broken symlinks
        if [ -e "$homelinkpath" ]; then
            echo "   * $homelinkpath already exists, skipping..."
        else
            echo "   * Linking $realfilepath to $homelinkpath..."
            ln -sf "$realfilepath" "$homelinkpath"
        fi
    fi
done

# scriptdir="${datadir}scripts"
# homebindir="$HOME/bin"
# if [ -d "$scriptdir" ]; then
#     echo " * Symlinking user scripts to $HOME/bin"
#     mkdir -p "$homebindir"
#     for file in "$scriptdir"*; do
#         basefilename=$( basename "$file" )
#         realfilepath=$( realpath "$file" )
#         binlinkpath="$homebindir/$basefilename"
#         if [ -e "$binlinkpath" ]; then
#             echo "   * $binlinkpath already exists, skipping..."
#         elif [ -f "$file" ]; then
#             echo "   * Linking $realfilepath to $binlinkpath..."
#             ln -sf "$realfilepath" "$binlinkpath"
#         fi
#     done
#     # shellcheck disable=SC2016
#     echo 'export PATH=$HOME/bin:$PATH' >> "$shrc"
# fi

# finish setting up zoxide
# shellcheck disable=SC2016,SC2129
echo 'eval "$(zoxide init bash)"' >> "$shrc_tmp"

# shellcheck disable=SC2129
echo >> "$shrc_tmp"
echo "# end sherry" >> "$shrc_tmp"
echo >> "$shrc_tmp"

if ! bash -n "$shrc_tmp"; then
    echo "The staged Bash configuration is invalid; $shrc was not changed." >&2
    exit 1
fi

mv -- "$shrc_tmp" "$shrc_target"
shrc_tmp=''
